import type { Metadata } from 'next';
import type { ReactNode } from 'react';
import './globals.css';
import { I18nProvider } from 'next-i18next/client';
import {
  generateI18nStaticParams,
  getResources,
  getT,
  initServerI18next,
} from 'next-i18next/server';
import ToasterProvider from '@/components/toaster-provider';
import i18nConfig from '../../i18n.config';

export const metadata: Metadata = {
  title: 'Booking Ticket',
  description: 'Generated by create next app',
};

initServerI18next(i18nConfig);

export async function generateStaticParams() {
  return generateI18nStaticParams();
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  const { i18n } = await getT();
  const resources = getResources(i18n);

  return (
    <html lang={locale} className={'h-full font-sans text-sm text-text antialiased'}>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&display=swap"
        />
      </head>
      <body className="flex min-h-full flex-col">
        <I18nProvider language={locale} resources={resources}>
          <ToasterProvider />
          {children}
        </I18nProvider>
      </body>
    </html>
  );
}
